//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nour_El_7abib_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quantity
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Quantity1 { get; set; }
        public double Weight { get; set; }
        public double TotalWeight { get; set; }
        public double Price { get; set; }
        public double TotalPrice { get; set; }
        public int CustomerId { get; set; }
        public double Charge { get; set; }
        public string Notes { get; set; }
        public string Type { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
